### PR TITLE
fix: f5aa05e upstream update compilation errors

### LINKED ISSUE #666: Cleanup tx's `result.deployments`
At some point in time we added this concept of “deployments”, which I believe was necessary because we couldn’t detect the deployments anymore, but now we have proper traces, so we should be able to clean this up.

https://github.com/matter-labs/foundry-zksync/blob/2aa8fa7dba6759767ae6bf6c3e6c4ccd16a5f9ca/crates/forge/src/runner.rs#L127

### PR DESCRIPTION
**Pull request by elfedy**
# What :computer: 
Fixing compilation errors for f5aa05e upstream update.

# Evidence :camera:
binaries compile

NOTE: Probably best reviewed by commit

### CODE REVIEW

File: crates/cheatcodes/src/inspector.rs [hunk 1]
```diff
@@ -69,7 +68,7 @@ use revm::{
 };
 use serde_json::Value;
 use std::{
-    collections::{BTreeMap, HashMap, HashSet, VecDeque},
+    collections::{BTreeMap, HashMap as sHashMap, HashSet, VecDeque},
```
Comment (nbaztec) [inline crates/cheatcodes/src/inspector.rs:71]: The idiomatic way is to state `use revm::HashMap as rHashMap` but perhaps we don't need this and can simply use revm's `HashMap`

File: crates/cheatcodes/src/inspector.rs [hunk 2]
```diff
@@ -545,7 +571,7 @@ pub struct Cheatcodes {
     /// would be a significant refactor, we maintain the factory_dep part in the [Cheatcodes].
     /// This can be done as each test runs with its own [Cheatcodes] instance, thereby
     /// providing the necessary level of isolation.
-    pub persisted_factory_deps: HashMap<H256, Vec<u8>>,
+    pub persisted_factory_deps: sHashMap<H256, Vec<u8>>,
```
Comment (nbaztec) [inline crates/cheatcodes/src/inspector.rs:574]: See above

File: crates/script/src/simulate.rs [hunk 3]
```diff
@@ -113,9 +113,10 @@ impl PreSimulationState {
         // Executes all transactions from the different forks concurrently.
         let futs = transactions
             .into_iter()
-            .map(|transaction| async {
+            .map(|mut transaction| async {
```
Comment (nbaztec) [inline crates/script/src/simulate.rs:116]: why the mut?

File: crates/cheatcodes/src/inspector.rs (hunk 1 above)
Comment (Karrq) [reply crates/cheatcodes/src/inspector.rs:71]: btw revm's HashMap belongs to alloy_primitives since last update I believe

File: crates/evm/evm/src/executors/mod.rs [hunk 4]
```diff
@@ -823,14 +812,11 @@ pub struct RawCallResult {
     pub out: Option<Output>,
     /// The chisel state
     pub chisel_state: Option<(Vec<U256>, Vec<u8>, InstructionResult)>,
-    /// The deployments generated during the call
-    pub deployments: HashMap<Address, Bytes>,
```
Comment (Karrq) [inline crates/evm/evm/src/executors/mod.rs:827]: Closes https://github.com/matter-labs/foundry-zksync/issues/666

File: crates/script/src/simulate.rs (hunk 3 above)
Comment (Karrq) [reply crates/script/src/simulate.rs:116]: later it's used for `tx` with `transaction.tx_mut()`, but it's vestigial and not needed - had the same thing during my update

Comment (Karrq) [reply crates/script/src/simulate.rs:116]: The upstream foundry code https://github.com/foundry-rs/foundry/blob/736a3300234a0921b9d8adde6c0c4dd14053ec8a/crates/script/src/simulate.rs#L115-L150 doesn't make use of the mutability

File: crates/script/src/simulate.rs [hunk 5]
```diff
@@ -113,9 +113,10 @@ impl PreSimulationState {
...
                 let mut runner = runners.get(&transaction.rpc).expect("invalid rpc url").write();
 
+                let zk_metadata = transaction.zk.clone();
```
[the remark this answers is not in the document]
Comment (Karrq) [reply crates/script/src/simulate.rs:119]: I think also because `transaction` is later `&mut` borrowed (at `tx_mut`) so we can't get the field by itself

File: crates/cheatcodes/src/inspector.rs [hunk 6]
```diff
@@ -154,13 +153,40 @@ pub trait CheatcodesExecutor {
...
-        &mut self,
-        ccx_state: &mut Cheatcodes,
-        ecx: &mut Ecx,
-        call_traces: Vec<Call>,
-    ) {
-        self.get_inspector(ccx_state).trace_zksync(ecx, call_traces);
+    fn trace_zksync(&mut self, ccx_state: &mut Cheatcodes, ecx: Ecx, call_traces: Vec<Call>) {
+        let mut inspector = self.get_inspector(ccx_state);
+
+        // We recreate the EvmContext here to satisfy the lifetime parameters as 'static, with
```
Comment (Karrq) [inline crates/cheatcodes/src/inspector.rs:159]: I don't quite understand this - where does the static bound show up?

File: crates/cheatcodes/src/inspector.rs (hunk 1 above)
Comment (elfedy) [reply crates/cheatcodes/src/inspector.rs:71]: I tried using alloy's `HashMap` everywhere when possible (because foundry now does that, there's no std HashMap) but it ends up clashing with some `zksync` libraries that do use the std HashMap. Imo, aliasing the the standard one is the lesser evil because it is the usage that differes from upstream, this way we have less merge conflicts.

File: crates/cheatcodes/src/inspector.rs (hunk 6 above)
Comment (nbaztec) [reply crates/cheatcodes/src/inspector.rs:159]: The `'static` is probably a misnomer, should've written it as 
> We recreate the EvmContext here to enforce the `Ecx` lifetime is completely contained within that of the inspector's as the compiler can no longer infer it.

In the code here https://github.com/matter-labs/foundry-zksync/blob/5e12e76ffbd55c777bd255ada1e5622dcd01a416/crates/cheatcodes/src/inspector.rs#L162 we use `&mut self` and `&mut ccx_state` to obtain the inspector which returns `Box<dyn InspectorExt + 'a>`, this does not play well with the compiler when we perform `trace_zksync(ecx)` which is now defined as `Ecx<'a, 'b, 'c> = &'a mut EvmContext<&'b mut (dyn DatabaseExt + 'c)>` so the compiler assumptions are broken as `&mut T` is invariant over `T`, causing us to explicitly define the lifetimes and their relationships as done in this commit [here ](https://github.com/matter-labs/foundry-zksync/blob/5e12e76ffbd55c777bd255ada1e5622dcd01a416/crates/cheatcodes/src/inspector.rs#L156)

The problem being, that we'd need to bubble this up several layers right upto the revm hook which we cannot update, in addition to being nasty.

That's why we redefine `&mut Ecx` by recreating it here.

File: crates/cheatcodes/src/inspector.rs (hunk 1 above)
Comment (elfedy) [reply crates/cheatcodes/src/inspector.rs]: Actually I found some more case I could use alloy's HashMap vs std

File: crates/cheatcodes/src/inspector.rs (hunk 2 above)
Comment (elfedy) [reply crates/cheatcodes/src/inspector.rs]: updated to use alloy's HashMap

File: crates/script/src/simulate.rs (hunk 3 above)
Comment (Karrq) [reply crates/script/src/simulate.rs:116]: Yeah it was part of "submit upstream patches" on my side, just didn't get around much to it

File: crates/script/src/simulate.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (elfedy) [reply crates/script/src/simulate.rs:119]: `tx_mut()` takes a mutable reference to transaction but returns another type that does not have zk fields, you cannot get it from `transaction` because `tx` is holding the reference
