### PR TITLE
fix: Encode correctly paymaster input

### LINKED ISSUE #756: "failed pre-paymaster preparation" when running forge create with paymaster
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (27360d4 2024-11-28T00:50:59.582122000Z)

### What command(s) is the bug in?

forge create ./contracts/util/SignatureChecker.sol:SignatureChecker --rpc-url testnet --private-key $DEPLOYER_PRIVATE_KEY --zksync --zk-paymaster-address $PAYMASTER_ADDRESS --zk-paymaster-input $(cast calldata "general(bytes)" "0x")

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
forge create ./contracts/util/SignatureChecker.sol:SignatureChecker --rpc-url testnet --private-key $DEPLOYER_PRIVATE_KEY --zksync --zk-paymaster-address $PAYMASTER_ADDRESS --zk-paymaster-input $(cast calldata "general(bytes)" "0x")

[⠃] Using zksolc-1.3.19
[⠊] Compiling (zksync)
No files changed, compilation skipped
Error: server returned an error response: error code 3: failed pre-paymaster preparation. error message: Error function_selector = 0xff15b069, data = 0xff15b069, data: "0x"
```

### PR DESCRIPTION
**Pull request by Jrigada**
# What :computer: 
* With the removal of zksync-web3-rs crate the way clap was treating the incoming paymaster input was leading to an error encoding the bytes.

### CODE REVIEW

**Review by nbaztec — DISMISSED** [review]
Possible to have a test?

**Review by elfedy — DISMISSED** [review]

File: crates/forge/tests/it/zk/paymaster.rs [hunk 1]
```diff
@@ -36,6 +36,95 @@ async fn test_zk_contract_paymaster() {
     assert!(cmd.assert_success().get_output().stdout_lossy().contains("Suite result: ok"));
 }
 
+// Tests the deployment of contracts using a paymaster for fee abstraction
+forgetest_async!(deploy_with_paymaster, |prj, cmd| {
```
Comment (Karrq) [inline crates/forge/tests/it/zk/paymaster.rs:40]:
```suggestion
forgetest_async!(test_zk_deploy_with_paymaster, |prj, cmd| {
```

**Review by Karrq — APPROVED** [review]
